title: Virtual and Augmented Reality Cognition Group
logo: /assets/img/logo.png
description:
url: 'https://vr-davis-group.github.io'
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
